import { useState, useEffect } from 'react';
import { Download, Share2, Copy, Check, FileJson, FileText, Loader2 } from 'lucide-react';
import { Button } from '@/components/ui/button';
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card';
import { Badge } from '@/components/ui/badge';
import type { AnalysisResults } from '../types';
import { useAnalysisStore } from '../hooks/use-analysis-store';

function formatMarkdownReport(results: AnalysisResults, prUrl?: string): string {
  const allIssues = [
    ...results.crossModalIssues,
    ...results.accessibilityIssues,
    ...results.uiIssues,
    ...results.codeIssues,
  ];

  let md = `# NovaLens Analysis Report\n\n`;
  md += `**Score:** ${results.score}/100\n`;
  if (prUrl) md += `**PR:** ${prUrl}\n`;
  md += `**Generated:** ${new Date().toISOString()}\n\n`;
  md += `## Summary\n${results.summary}\n\n`;
  md += `## Issues Found (${allIssues.length})\n\n`;

  const categories = [
    { key: 'cross-modal', label: 'Cross-Modal Issues', issues: results.crossModalIssues },
    { key: 'accessibility', label: 'Accessibility Issues', issues: results.accessibilityIssues },
    { key: 'ui', label: 'UI Issues', issues: results.uiIssues },
    { key: 'code', label: 'Code Issues', issues: results.codeIssues },
  ];

  for (const cat of categories) {
    if (cat.issues.length === 0) continue;
    md += `### ${cat.label} (${cat.issues.length})\n\n`;
    for (const issue of cat.issues) {
      const severityEmoji =
        issue.severity === 'critical' ? '🔴' :
        issue.severity === 'major' ? '🟠' :
        issue.severity === 'minor' ? '🟡' : '🔵';
      md += `${severityEmoji} **${issue.title}** [${issue.severity}]\n`;
      md += `${issue.description}\n`;
      if (issue.location) md += `📍 \`${issue.location}\`\n`;
      if (issue.suggestion) md += `💡 ${issue.suggestion}\n`;
      if (issue.fixCode) md += `\`\`\`\n${issue.fixCode}\n\`\`\`\n`;
      md += `\n`;
    }
  }

  md += `---\n*Generated by [NovaLens](https://github.com/buddypia/novalens) — AI Visual Code Review Agent*\n`;
  return md;
}

function downloadFile(content: string, filename: string, mimeType: string) {
  const blob = new Blob([content], { type: mimeType });
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url;
  a.download = filename;
  document.body.appendChild(a);
  a.click();
  document.body.removeChild(a);
  URL.revokeObjectURL(url);
}

export function ReportActions() {
  const { currentAnalysis } = useAnalysisStore();
  const results = currentAnalysis?.results;
  const [copied, setCopied] = useState(false);
  const [isExporting, setIsExporting] = useState(false);
  const [shareUrl, setShareUrl] = useState('');

  useEffect(() => {
    // Generate share URL on mount
    if (currentAnalysis?.id) {
      setShareUrl(`${window.location.origin}/analysis/${currentAnalysis.id}`);
    }
  }, []);

  if (!results) return null;

  const totalIssues =
    results.uiIssues.length +
    results.codeIssues.length +
    results.crossModalIssues.length +
    results.accessibilityIssues.length;

  const handleExportJSON = () => {
    setIsExporting(true);
    const data = {
      analysisId: currentAnalysis?.id,
      score: results.score,
      summary: results.summary,
      prUrl: currentAnalysis?.input.prUrl,
      exportedAt: new Date().toISOString(),
      issues: {
        crossModal: results.crossModalIssues,
        accessibility: results.accessibilityIssues,
        ui: results.uiIssues,
        code: results.codeIssues,
      },
    };
    downloadFile(JSON.stringify(data, null, 2), `novalens-report-${currentAnalysis?.id}.json`, 'application/json');
    setIsExporting(false);
  };

  const handleExportMarkdown = () => {
    const md = formatMarkdownReport(results, currentAnalysis?.input.prUrl);
    downloadFile(md, `novalens-report-${currentAnalysis?.id}.md`, 'text/markdown');
  };

  const handleCopyShareLink = async () => {
    await navigator.clipboard.writeText(shareUrl);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  const handleShareToGitHub = () => {
    const md = formatMarkdownReport(results, currentAnalysis?.input.prUrl);
    const prUrl = currentAnalysis?.input.prUrl;
    if (prUrl) {
      const commentUrl = `${prUrl}#issuecomment-new`;
      navigator.clipboard.writeText(md);
      window.open(commentUrl, '_blank');
    }
  };

  return (
    <Card>
      <CardHeader>
        <CardTitle className="flex items-center justify-between text-base">
          <div className="flex items-center gap-2">
            <Share2 className="h-4 w-4" />
            Export & Share
          </div>
          <Badge variant="secondary" className="text-xs">
            {totalIssues} issues
          </Badge>
        </CardTitle>
      </CardHeader>
      <CardContent className="space-y-3">
        {/* Export Options */}
        <div className="space-y-2">
          <p className="text-xs font-medium" style={{ color: '#999' }}>Download Report</p>
          <div className="grid grid-cols-2 gap-2">
            <Button
              variant="outline"
              size="sm"
              className="justify-start gap-2"
              onClick={handleExportJSON}
            >
              {isExporting ? (
                <Loader2 className="h-3.5 w-3.5 animate-spin" />
              ) : (
                <FileJson className="h-3.5 w-3.5" />
              )}
              JSON
            </Button>
            <Button
              variant="outline"
              size="sm"
              className="justify-start gap-2"
              onClick={handleExportMarkdown}
            >
              <FileText className="h-3.5 w-3.5" />
              Markdown
            </Button>
          </div>
        </div>

        {/* Share Link */}
        <div className="space-y-2">
          <p className="text-xs font-medium" style={{ color: '#999' }}>Share Link</p>
          <div className="flex gap-2">
            <div
              className="flex-1 truncate rounded-md border bg-muted/50 px-3 py-1.5 font-mono text-xs"
              title={shareUrl}
              onClick={handleCopyShareLink}
            >
              {shareUrl || 'Generating...'}
            </div>
            <Button
              variant="outline"
              size="sm"
              onClick={handleCopyShareLink}
            >
              {copied ? (
                <Check className="h-3.5 w-3.5 text-emerald-500" />
              ) : (
                <Copy className="h-3.5 w-3.5" />
              )}
            </Button>
          </div>
        </div>

        {/* Post to GitHub PR */}
        {currentAnalysis?.input.prUrl && (
          <div
            className="flex cursor-pointer items-center gap-2 rounded-lg border border-dashed p-3 text-xs transition-colors hover:bg-muted/50"
            onClick={handleShareToGitHub}
          >
            <Download className="h-4 w-4 text-muted-foreground" />
            <div>
              <p className="font-medium">Post to GitHub PR</p>
              <p style={{ color: '#aaa' }}>
                Copies report to clipboard and opens the PR comment page
              </p>
            </div>
          </div>
        )}
      </CardContent>
    </Card>
  );
}
