import { useState } from 'react';
import { Copy, Check, FileCode, MessageSquare, ClipboardList } from 'lucide-react';
import { Button } from '@/components/ui/button';
import { Card, CardContent } from '@/components/ui/card';
import { Badge } from '@/components/ui/badge';
import { Tabs, TabsContent, TabsList, TabsTrigger } from '@/components/ui/tabs';
import type { Issue, AnalysisResults } from '../types';
import { SEVERITY_ORDER } from '../types';
import { useAnalysisStore } from '../hooks/use-analysis-store';

function getIssuesWithFix(results: AnalysisResults): Issue[] {
  return [
    ...results.uiIssues,
    ...results.codeIssues,
    ...results.crossModalIssues,
    ...results.accessibilityIssues,
  ]
    .filter((issue) => issue.fixCode)
    .sort((a, b) => SEVERITY_ORDER[a.severity] - SEVERITY_ORDER[b.severity]);
}

function getAllIssues(results: AnalysisResults): Issue[] {
  return [
    ...results.uiIssues,
    ...results.codeIssues,
    ...results.crossModalIssues,
    ...results.accessibilityIssues,
  ].sort((a, b) => SEVERITY_ORDER[a.severity] - SEVERITY_ORDER[b.severity]);
}

function severityEmoji(severity: Issue['severity']): string {
  switch (severity) {
    case 'critical': return '\u{1F6A8}';
    case 'major': return '\u26A0\uFE0F';
    case 'minor': return '\u{1F4A1}';
    case 'info': return '\u2139\uFE0F';
  }
}

function generateReviewComment(results: AnalysisResults, prTitle?: string): string {
  const allIssues = getAllIssues(results);
  const lines: string[] = [];

  lines.push(`## \u{1F50D} NovaLens AI Code Review`);
  if (prTitle) lines.push(`> **PR**: ${prTitle}`);
  lines.push('');
  lines.push(`**Score**: ${results.score}/100 | **Issues**: ${allIssues.length} found`);
  lines.push('');
  lines.push(`> ${results.summary}`);
  lines.push('');

  const categories = [
    { label: 'Cross-Modal Issues', issues: results.crossModalIssues },
    { label: 'Accessibility Issues', issues: results.accessibilityIssues },
    { label: 'UI Issues', issues: results.uiIssues },
    { label: 'Code Issues', issues: results.codeIssues },
  ];

  for (const cat of categories) {
    if (cat.issues.length === 0) continue;
    lines.push(`### ${cat.label} (${cat.issues.length})`);
    lines.push('');

    for (const issue of cat.issues.sort((a, b) => SEVERITY_ORDER[a.severity] - SEVERITY_ORDER[b.severity])) {
      lines.push(`${severityEmoji(issue.severity)} **[${issue.severity.toUpperCase()}]** ${issue.title}`);
      if (issue.location) lines.push(`  - \u{1F4CD} \`${issue.location}\``);
      lines.push(`  - ${issue.description}`);
      if (issue.suggestion) lines.push(`  - \u{1F527} **Fix**: ${issue.suggestion}`);
      if (issue.fixCode) {
        lines.push('  ```suggestion');
        lines.push(`  ${issue.fixCode}`);
        lines.push('  ```');
      }
      lines.push('');
    }
  }

  lines.push('---');
  lines.push('*Generated by [NovaLens](https://github.com/buddypia/novalens) - AI Visual Code Review Agent*');

  return lines.join('\n');
}

function generateSuggestedChanges(results: AnalysisResults): string {
  const fixIssues = getIssuesWithFix(results);
  if (fixIssues.length === 0) return '// No fix suggestions available';

  const lines: string[] = [];
  lines.push('## \u{1F527} Suggested Changes');
  lines.push('');
  lines.push('> Copy each suggestion block into the PR comment. GitHub will show an "Apply suggestion" button.');
  lines.push('');

  for (const issue of fixIssues) {
    lines.push(`### ${severityEmoji(issue.severity)} ${issue.title}`);
    if (issue.location) lines.push(`**File**: \`${issue.location}\``);
    if (issue.suggestion) lines.push(`> ${issue.suggestion}`);
    lines.push('');
    lines.push('```suggestion');
    lines.push(issue.fixCode!);
    lines.push('```');
    lines.push('');
  }

  return lines.join('\n');
}

function generateFileGrouped(results: AnalysisResults): string {
  const allIssues = getAllIssues(results);
  const fileMap = new Map<string, Issue[]>();

  for (const issue of allIssues) {
    const file = issue.location?.split(':')[0] ?? '(unknown file)';
    const existing = fileMap.get(file) ?? [];
    existing.push(issue);
    fileMap.set(file, existing);
  }

  const lines: string[] = [];
  lines.push('## \u{1F4C1} Issues by File');
  lines.push('');

  for (const [file, issues] of fileMap) {
    lines.push(`### \`${file}\` (${issues.length} issues)`);
    lines.push('');

    for (const issue of issues) {
      const line = issue.location?.split(':')[1];
      const lineRef = line ? ` (L${line})` : '';
      lines.push(`- ${severityEmoji(issue.severity)} **${issue.title}**${lineRef}`);
      lines.push(`  ${issue.description}`);
      if (issue.fixCode) {
        lines.push('  ```suggestion');
        lines.push(`  ${issue.fixCode}`);
        lines.push('  ```');
      }
    }
    lines.push('');
  }

  return lines.join('\n');
}

function CopyButton({ text, label }: { text: string; label: string }) {
  const [copied, setCopied] = useState(false);

  const handleCopy = async () => {
    await navigator.clipboard.writeText(text);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  return (
    <Button
      onClick={handleCopy}
      variant={copied ? 'default' : 'outline'}
      size="sm"
      className="gap-2"
    >
      {copied ? (
        <>
          <Check className="h-4 w-4" />
          Copied!
        </>
      ) : (
        <>
          <Copy className="h-4 w-4" />
          {label}
        </>
      )}
    </Button>
  );
}

export function ReviewExportPanel() {
  const { currentAnalysis } = useAnalysisStore();
  const results = currentAnalysis?.results;

  if (!results) return null;

  const allIssues = getAllIssues(results);
  const fixCount = getIssuesWithFix(results).length;

  if (allIssues.length === 0) return null;

  const reviewComment = generateReviewComment(results, currentAnalysis.input.prTitle);
  const suggestedChanges = generateSuggestedChanges(results);
  const fileGrouped = generateFileGrouped(results);

  return (
    <Card>
      <CardContent className="pt-6">
        <div className="mb-4 flex items-center justify-between">
          <div className="flex items-center gap-2">
            <ClipboardList className="h-5 w-5 text-primary" />
            <h3 className="text-lg font-semibold">Export to PR</h3>
          </div>
          <Badge variant="secondary">
            {fixCount} fix suggestions
          </Badge>
        </div>
        <p className="mb-4 text-sm text-muted-foreground">
          Copy the review below and paste it into your GitHub PR comment.
        </p>

        <Tabs defaultValue="review-comment">
          <TabsList className="w-full justify-start">
            <TabsTrigger value="review-comment" className="gap-1.5">
              <MessageSquare className="h-3.5 w-3.5" />
              Full Review
            </TabsTrigger>
            <TabsTrigger value="suggested-changes" className="gap-1.5">
              <FileCode className="h-3.5 w-3.5" />
              Suggestions Only
            </TabsTrigger>
            <TabsTrigger value="file-grouped" className="gap-1.5">
              <ClipboardList className="h-3.5 w-3.5" />
              By File
            </TabsTrigger>
          </TabsList>

          <TabsContent value="review-comment">
            <div className="space-y-3">
              <CopyButton text={reviewComment} label="Copy Full Review" />
              <pre className="max-h-96 overflow-auto rounded-lg border bg-muted/50 p-4 text-xs leading-relaxed">
                {reviewComment}
              </pre>
            </div>
          </TabsContent>

          <TabsContent value="suggested-changes">
            <div className="space-y-3">
              <CopyButton text={suggestedChanges} label="Copy Suggestions" />
              {fixCount === 0 ? (
                <p className="py-4 text-center text-sm text-muted-foreground">
                  No fix code suggestions in the analysis results.
                </p>
              ) : (
                <pre className="max-h-96 overflow-auto rounded-lg border bg-muted/50 p-4 text-xs leading-relaxed">
                  {suggestedChanges}
                </pre>
              )}
            </div>
          </TabsContent>

          <TabsContent value="file-grouped">
            <div className="space-y-3">
              <CopyButton text={fileGrouped} label="Copy File Report" />
              <pre className="max-h-96 overflow-auto rounded-lg border bg-muted/50 p-4 text-xs leading-relaxed">
                {fileGrouped}
              </pre>
            </div>
          </TabsContent>
        </Tabs>
      </CardContent>
    </Card>
  );
}
